[features]
seeds = false
skip-lint = false
[programs.localnet]
ousia-burn-and-mint = "Fa63c9tRsE3uJ3GQ7q22KAWq38pq4tfyR2AkqpCprgay"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/devenv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
match = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transactionMatcher.ts"
