[features]
seeds = false
skip-lint = false
[programs.localnet]
collateralized_debt = "EXeqAfY6BiBZbvbdGsw1EZgXapQMrJeLkGhEVCigAF6u"
ousia_burn_and_mint = "HrDmYNghkxXBWEfQTt4ZdpMdBc2MNbtJsjPJA6dtNUzP"

[programs.devnet]
collateralized_debt = "EXeqAfY6BiBZbvbdGsw1EZgXapQMrJeLkGhEVCigAF6u"
ousia_burn_and_mint = "HrDmYNghkxXBWEfQTt4ZdpMdBc2MNbtJsjPJA6dtNUzP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/devenv/.config/solana/id.json"

[scripts]
match = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transactionMatcher.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/collateralized-debt.ts"
